server:
  port: 8080

spring:
  application:
    name: mycat
  thymeleaf:
    cache: false # 关闭缓存
    mode: LEGACYHTML5 # 去除htm5严格校验
    prefix: classpath:/templates/ # 指定 thymeleaf 模板路径
    encoding: UTF-8 # 指定字符集编码
    suffix: .html
  mvc:
    static-path-pattern: /static/** # js ,css 等静态文件路径
